version: '3'

dotenv: ['.env', '.env.example']

vars:
  IMAGE_TAG: 'rexasi-tracker/tracker'
  DOCKER_COMPOSE_CMD: 'docker compose'
  DOCKER_FLAGS: '--network rexasi-tracker --rm -it'

includes:
  tracker: ./tasks/tracker.yml
  example: ./tasks/example.yml
  detectors: ./tasks/detectors.yml

env:
  DOCKER_BUILDKIT: 1 

tasks:

  clean:
    cmds:
      - sudo rm -rf build install log resource
      - mkdir -p data
      - sudo chmod -R 777 ./data

  setup:
    cmds:
      - docker network create rexasi-tracker | true
      - task tracker:build
      - task detectors:setup
      - task example:setup
      - '[ ! -f .env ] && cp .env.example .env || true'

  start-tracker:
    cmds:
      - task tracker:start

  start-example:
    cmds:
      - task example:start-rgbd

  start-multiple-run-lidar:
    cmds:
      - xhost local:root
      - SENSOR=LIDAR bash multiple-run.sh

  start-multiple-run-rgbd:
    cmds:
      - xhost local:root
      - SENSOR=RGBD bash multiple-run.sh
  
  start-multiple-run-custom:
    cmds:
      - SENSOR=CUSTOM TRACKER_COMPOSE_FILE={{.TRACKER_COMPOSE_FILE}} bash multiple-run.sh

  start-test:
    cmds:
      - xhost local:root
      - EXPERIMENT="s2" INPUT_DIRECTORY={{.INPUT_DIRECTORY_TEST}} {{.DOCKER_COMPOSE_CMD}} -f example/docker-compose-rgbd.yaml up -d
      - docker wait player
      - E=A {{.DOCKER_COMPOSE_CMD}} -f example/docker-compose-rgbd.yaml kill
      - E=A {{.DOCKER_COMPOSE_CMD}} -f example/docker-compose-rgbd.yaml down
      - cp ../tracker-output-tmp/tracker_output.csv ../evaluation-data-test/s2/
      
  rviz:
    cmds:
      - xhost local:root
      - docker run --name rviz -v /tmp/.X11-unix:/tmp/.X11-unix:rw -e DISPLAY=$DISPLAY {{.DOCKER_FLAGS}} {{.BASE_IMAGE_TAG}} ros2 run rviz2 rviz2

  bash:
    cmds:
      - docker run {{.DOCKER_FLAGS}} {{.IMAGE_TAG}} bash

  stop:
    cmds:
      - '{{.DOCKER_COMPOSE_CMD}} -f example/docker-compose-lidar.yaml kill'
      - '{{.DOCKER_COMPOSE_CMD}} -f example/docker-compose-rgbd.yaml kill'
      - '{{.DOCKER_COMPOSE_CMD}} -f docker/docker-compose.yaml kill'
      - '{{.DOCKER_COMPOSE_CMD}} -f example/docker-compose-lidar.yaml down'
      - '{{.DOCKER_COMPOSE_CMD}} -f example/docker-compose-rgbd.yaml down'
      - '{{.DOCKER_COMPOSE_CMD}} -f docker/docker-compose.yaml down'
