networks:
  rexasi-tracker:
    name: "rexasi-tracker"
    external: true

include:
  - ../docker/docker-compose.yaml

services:
  rgbd-detector-left:
    container_name: rgbd-detector-left
    extends:
      file: ../docker/docker-compose.detectors.yaml
      service: rgbd-detector
    command: ros2 launch rgbd_detector launch.py pose_output_topic:=/keypoints_camera_1 keypoints_topic:=/keypoints_camera_1 rgbd_color_topic:=/camera_1/color/image_raw optical_frame_id:=camera_1_color_optical_frame rgbd_depth_topic:=/camera_1/depth/image_rect_raw rgbd_depth_camera_info_topic:=/camera_1/depth/camera_info sensor_id:=2
  rgbd-detector-right:
    container_name: rgbd-detector-right
    extends:
      file: ../docker/docker-compose.detectors.yaml
      service: rgbd-detector
    command: ros2 launch rgbd_detector launch.py pose_output_topic:=/keypoints_camera_2 keypoints_topic:=/keypoints_camera_2 rgbd_color_topic:=/camera_2/color/image_raw optical_frame_id:=camera_2_color_optical_frame rgbd_depth_topic:=/camera_2/depth/image_rect_raw rgbd_depth_camera_info_topic:=/camera_2/depth/camera_info sensor_id:=3
  player:
    depends_on:
      - rexasi-tracker
    container_name: player
    image: rexasi-tracker/rosbag
    build:
      context: ..
      dockerfile: example/Dockerfile
    command: bash -c "sleep 10 && ros2 bag play /sequences/${EXPERIMENT}"
    volumes:
      - ../${INPUT_DIRECTORY}:/sequences
    networks:
      - rexasi-tracker
  logger:
    container_name: logger
    image: rexasi-tracker/logger
    build:
      context: ..
      dockerfile: docker/Dockerfile.logger
    command: ros2 launch rexasi_logger launch.py
    volumes:
      - ../../tracker-output-tmp:/data
    networks:
      - rexasi-tracker
  rviz:
    container_name: rviz
    image: rexasi-tracker/base
    command: ros2 run rviz2 rviz2
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rviz:/root/.rviz2/
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - rexasi-tracker
